### ISSUE TITLE
SpectrumExtractor::PickSpectrum

### ISSUE THREAD

**Issue by dmccloskey** [biosustain/OpenMS#11]
pick peaks in a spectrum.  This function will be modeled closely off of the PeakPickerMRM class (i.e., first filter using a gausian or svgolay filter and then pick using PeakPickerHiRes).  The function call order to ExtractSpectrum will then be 1. PickSpectrum, 2. AnnotateSpectrum, 3. ScoreSpectrum, and 4. MatchSpectrum.

**Comment by pcolaianni** [comment]
https://github.com/biosustain/OpenMS/commit/fbae18adb039cc7cb3f6479152172dc3bf29824b
