### ISSUE TITLE
AbsoluteQuantitation::optimizeCalibrationCurves LLOQ and ULOQ

### ISSUE THREAD

**Issue by dmccloskey** [biosustain/OpenMS#113]
### Description
The values chosen for the LLOQ and ULOQ are not correct when an optimal set of calibration points is not found.

### Fix
use `std::min_element` and `std::max_element` (see http://www.cplusplus.com/reference/algorithm/min_element/ for reference)

**Comment by pcolaianni** [comment]
check lines 627 628 and update tests
