### ISSUE TITLE
Advanced Filter Flagging

### ISSUE THREAD

**Issue by dmccloskey** [biosustain/OpenMS#116]
### Description
Improvements to the ability to flag and filter features.

### Objectives
- [x] Single value summary statistic on a component and component_group quality
- [x] Additional filter criteria for component_groups

### Summary statistic for component and component group
- component/component_group quality score = 1/(n QC metrics)*binary(0 or 1 for pass or fail) + ...
- change "QC_transition_pass" to "QC_transition_score" and also for QC_transition_group
- overall quality score for the component = (component quality score + component group quality score)/2 [ignore for now]

### Enhancements to MRMFeatureQC structs
- Struct members for retention_time, intensity, and overall_quality should be a part of ComponentGroupQCs as well as ComponentQCs
- ComponentGroupQCs is missing an attribute for metavalues similar to ComponentQCs

### Modifications required to MRMFeatureQC .csv template
- mechanisms to indicate when a metaValue is a component_group MetaValue or component MetaValue (note: feature ~ component_group, sub_feature ~ component)
- Add in "ComponentQCs_" and "ComponentGroupQCs_" to differentiate between parameters that go into the `ComponentQCs` and which go into the  `ComponentGroupQCs`

### Classes to update ###
- MRMFeatureFilter
- MRMFeatureQC
- MRMFeatureQCFile

**Comment by dmccloskey** [comment]
I did not explicitly add it in, but we will need to update MRMFeatureFilter to utilize the new MRMFeatureQC structure.

**Comment by pcolaianni** [comment]
PR opened in OpenMS upstream repo.
