### ISSUE TITLE
Option for how to define concensus `best_left` and `best_right` 

### ISSUE THREAD

**Issue by dmccloskey** [biosustain/OpenMS#123]
### Description
Concensus `best_left` and `best_right` used in `MRMTransitionGroupPicker` to define the peak borders or all transitions in a transition group can lead to cutoff peaks (e.g., amp) or merged peaks (e.g., accoa).  This is due to the use of the largest peak to define the `best_left` and `best_right` (see line 168 `findLargestPeak(picked_chroms_, chr_idx, peak_idx);`)

### Fix
- An optional parameter to allow for using the largest peak to define the concensus `best_left` and `best_right` peak borders for all transitions (the current implementation).
- An optional parameter to use the peak with the largest total width to define the concensus `best_left` and `best_right` peak borders for all transitions.
- An optional parameter to not use any consensus  `best_left` and `best_right` (i.e., use the provided best_left and best_right for each individual transition)

### Examples
- [https://app.zenhub.com/files/101999003/1280f967-bafb-48ad-8604-64a0914f19e5/download](https://app.zenhub.com/files/101999003/1280f967-bafb-48ad-8604-64a0914f19e5/download)
- [https://app.zenhub.com/files/101999003/90976381-ba3f-4bb5-abfb-46fba00a72f4/download](https://app.zenhub.com/files/101999003/90976381-ba3f-4bb5-abfb-46fba00a72f4/download)

**Comment by pcolaianni** [comment]
We could close this one and create a new one only for the "no consensus boundaries" feature
