### ISSUE TITLE
HPLC Chromatogram pre-processing

### ISSUE THREAD

**Issue by dmccloskey** [biosustain/OpenMS#155]
# Description
Peaks on the lower end of the calibration curve (i.e., peaks with a small peak height and low s/n) are not identified during peak picking

# Objectives
- [x] implement a raw chromatogram filter that extracts specific retention time windows before peak picking
- [x] zero the baseline of the chromatogram so that no point is below 0 intensity while maintaining the relative intensity of all points in the chromatogram.

# Tests/Validation
1. split of a single HPLC chromatogram into e.g., 4 different chromatograms with subwindows (i.e., split chromatogram A [0-10 min] into chromatograms B1-4 of [0-2 min], [2-4 min], [4-8 min], [8-10 min]).  Note that the exact implementation will depend on the test data used.
2. zero the baseline of a chromatogram with multiple points that are below 0 signal intensity so that the resulting chromatogram has baseline subtracted peak heights that are the same as the original, but no intensity is below 0.

**Comment by pcolaianni** [comment]
The methods were merged, with names `removePeaks` and `subtractMinimumIntensity`
