### ISSUE TITLE
SpectrumExtractor::selectSpectra

### ISSUE THREAD

**Issue by dmccloskey** [biosustain/OpenMS#22]
Method for selecting the highest scoring spectra:

Input: `std::vector<MSSpectrum>` and `FeatureMap`
output: `std::vector<MSSpectrum>` and `FeatureMap`

**Comment by pcolaianni** [comment]
https://github.com/biosustain/OpenMS/commit/1b084aa3b64a973d279d82f914dbcc2907b0f7a4
