### ISSUE TITLE
SpectrumExtractor::scoreSpectrum refactor to generate a FeatureMap

### ISSUE THREAD

**Issue by dmccloskey** [biosustain/OpenMS#23]
Capture picked and scored information for each precursor and individual peak and score information for each peak within the MSSpectrum in a FeatureMap class.

Input:  `std::vector<MSSpectrum>` and empty `FeatureMap`
Input:  `std::vector<MSSpectrum>` and filled `FeatureMap`

**Comment by pcolaianni** [comment]
https://github.com/biosustain/OpenMS/commit/1b084aa3b64a973d279d82f914dbcc2907b0f7a4
