### ISSUE TITLE
Min/max peak height and FWHM threshold for picked peaks

### ISSUE THREAD

**Issue by dmccloskey** [biosustain/OpenMS#29]
If there is no min/max peakHeight and FWHM criteria provided by the peakPickerHiRes, this is something we should add in.  I was looking back through my notes, and there are instances in my downstream data processing that I would omit peaks based on these criteria.

Essentially it would be a check on each peak after peakPicking to make sure each peak falls within the min/max.

**Comment by pcolaianni** [comment]
@dmccloskey 
Should I add two parameters to the class? Like `peak_height_min_` and `peak_height_max_`?
This would be implemented in `pickSpectrum()`, right after `pp.pick(smoothed_spectrum, picked_spectrum);` and before returning from the method.

**Comment by pcolaianni** [comment]
Oh yeah, and I forgot about the eventual parameter for the fwhm, something like `FWHM_threshold_`. Then I would also check for this, and not only for min/max height.

**Comment by dmccloskey** [comment]
`peak_height_min` and `peak_height_max_` along with `FWHM_threshold_` would be good.  It should be implemented in pickSpectrum.

**Comment by pcolaianni** [comment]
What are good default values for those three parameters?
And what about minimum and maximum permitted values? (like with `setMinFloat()` etc.)
@dmccloskey
