### ISSUE TITLE
PeakIntegrator

### ISSUE THREAD

**Issue by dmccloskey** [biosustain/OpenMS#47]
links to issue https://github.com/OpenMS/OpenMS/issues/3003

**Comment by pcolaianni** [comment]
**Attributes**
- Integration_type = “intensity_sum”,”trapezoid”,”simpson”,[v2: ”gaussian”,”EMG”]
- Baseline_type = “vertical_division”, ”base_to_base”,[v2:  ”EMG_extrapolation”]
- Peak_model = “none”, [v2: “gaussian”, “EMG”]
  - EMG see

**Comment by hroest** [comment]
@dmccloskey @pasqoo please note that we have already models for EMG inside OpenMS that we could just repurpose, see OpenMS/TRANSFORMATIONS/FEATUREFINDER/EmgScoring.h and OpenMS/TRANSFORMATIONS/FEATUREFINDER/EmgModel.h

**Comment by pcolaianni** [comment]
I'm closing this since it is a generic issue. We can open a new issue with more details about future features to add to the class PeakIntegrator.
