### ISSUE TITLE
PeakIntegrator integratePeak()

### ISSUE THREAD

**Issue by pcolaianni** [biosustain/OpenMS#51]
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMTransitionGroupPicker.h#L538

Input: MSSpectrum/MSChromatogram
Input: double left (coordinates of mz or rt)
Input: double right
Internal: double peak_height
Internal: double peak_area
Internal: double peak_apex (coordinates of mz or rt)

**Comment by pcolaianni** [comment]
@dmccloskey what are the desired outputs? Should I output all those that you called "internal"? (meaning: `peak_height`, `peak_area`, `peak_apex`)?

**Comment by pcolaianni** [comment]
@dmccloskey Are `left` and `right` going to be equal to two peaks' positions?
Or should I take them as "take peaks that are within these two limits"?

**Comment by dmccloskey** [comment]
Sorry I did not see this mention until now. 

I am thinking either a getter to return each parameter individual or a struct to return all of them at once.  Let's start off with just getters and then move to a struct if it becomes apparent that that is more optimal.

Left and Right define the left and right borders of the peak (in mz or rt space).

**Comment by pcolaianni** [comment]
@dmccloskey the code is already merged, what I did is putting 3 "output" arguments for the method: https://github.com/biosustain/OpenMS/commit/feade87666583e98215a4f9b3a5e2de94f41d8df#diff-5dabca06382be88f2c44de77758c7b31R54
Should the three arguments become class' members or should everything stay like it is?

**Comment by dmccloskey** [comment]
I see.  We will have a lot of parameters, so I am thinking that making them class members and adding in attributes for returning their value would be more convenient and usable.
