### ISSUE TITLE
SpectrumExtractor::set/getParameters

### ISSUE THREAD

**Issue by dmccloskey** [biosustain/OpenMS#6]
1. getDefaultParameters
2. getParameters (that returns the default Param object)
3.  get/set methods for individual members:
a. rt_window 
b. mz_tolerance
c. mz_units (ppm or Da)
d. min_score
e. min_foward_match
f. min_reverse_match

**Comment by pcolaianni** [comment]
@dmccloskey What are sane defaults for those members? (should I use the identifier `mz_units` or `mz_tolerance_units`?)
