### ISSUE TITLE
Simpson integration, what if N of points is even but there is no additional right point

### ISSUE THREAD

**Issue by pcolaianni** [biosustain/OpenMS#66]
@dmccloskey 

Suppose an even number of points, and that there is no available additional point on the right side.

Should I try adding a point from the left side?

In general (supposing the additional point is available from both sides), should the background algorithm try to take the additional point from the side which has the higher intensity?

eg. left->int == 30, right->int == 40, I would first try to add the additional point from the right side (I expect, maybe wrongly, to have a lower intensity on that point, maybe closer to that of left->int). Is this idea useful or it doesn't reflect to real cases?

**Comment by dmccloskey** [comment]
This is actually a very important detail.  Let's try implementing the algorithm like this: 

1. calculate the peak area with one less point on the left
2. calculate the peak area with one less point on the right
3. try to calculate the peak area if there is an additional point on the right.
4. try to calculate the peak area if there is an additional point on the left
5. average the values of 1, 2, 3, and 4 (if 3 and 4 are possible).

I should note: It applies only to how the peak is integrated for simpsons rule.  It does not matter for the background estimation as either a rhombazoid (base_to_base) or rectangle (veritical_division) are calculated when the user specifies either the trapezoid rule or simpson's rule.

**Comment by pcolaianni** [comment]
https://github.com/biosustain/OpenMS/commit/597d9559a790b09b2f68b169dbf218f5463ff356
