### ISSUE TITLE
pyOpenMS support for custom struct

### ISSUE THREAD

**Issue by pcolaianni** [biosustain/OpenMS#71]
https://github.com/biosustain/OpenMS/commit/5530585b1b5481da313321755d07c16eb291c2e0
in that commit I implemented pyOpenMS support for the PeakIntegrator class.

I'm not sure I can use `PeakShapeMetrics_` as a type, though (at line 20).

Do you know more on this? @dmccloskey 

The problem is present only if the method `calculatePeakShapeMetrics` is to be exposed (you don't expose it in `MRMTransitionGroupPicker` class).

**Comment by dmccloskey** [comment]
This is a good point as the original implementation was meant to be as a private method of MRMTransitionGroupPicker.  

I am thinking that it might be best to not use a struct, but instead make each of the individual struct attributes, attributes of the class that are exposed to the user with a getter (similar to peak_area_, peak_height_, etc.).  How does this sound to you?

**Comment by pcolaianni** [comment]
It would be 16 additional members and getters. I will first look into how to wrap a custom struct in pyOpenMS (if it is possible to do so) and then see which solution we can better take advantage of.

**Comment by dmccloskey** [comment]
I think pyOpenMS can wrap the std::map class.  Maybe making all of them members, but then returning them as a std::map instead of a struct?

**Comment by pcolaianni** [comment]
That sounds good to me.

The user would give a string to get a member, like:
`peakShapeMetrics["start_time_at_50"]`
or
`peakShapeMetrics.at("start_time_at_50")`

I guess we wouldn't need to make them all members, but just the map itself. And its mapped values would be what the user would ask for. The same goes for the algorithm: it would set values on the map.

How does it sound?

**Comment by pcolaianni** [comment]
The struct attributes are class' members now.
Closing because not relevant anymore.

PS: An example of how to wrap a struct:
.pxd: https://github.com/OpenMS/OpenMS/blob/ec89b2f6406d19ba41d0137e64f6e7396736fffc/src/pyOpenMS/pxds/ConsensusFeature.pxd#L83
.h: https://github.com/OpenMS/OpenMS/blob/ec89b2f6406d19ba41d0137e64f6e7396736fffc/src/openms/include/OpenMS/KERNEL/ConsensusFeature.h#L116
